apiVersion: v1
kind: ServiceAccount
metadata:
  name: region-cluster-autoscaler
  namespace: cluster-autoscaler
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746669239459:role/cluster-autoscaler
---
apiVersion: v1
kind: Service
metadata:
  name: region-cluster-autoscaler
  namespace: cluster-autoscaler
  labels:
    app: region-cluster-autoscaler
spec:
  selector:
    app: region-cluster-autoscaler
  ports:
    - name: grpc
      port: 8086
      targetPort: 8086
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: region-cluster-autoscaler
  namespace: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: region-cluster-autoscaler
  template:
    metadata:
      labels:
        app: region-cluster-autoscaler
    spec:
      serviceAccountName: region-cluster-autoscaler
      priorityClassName: system-cluster-critical
      containers:
        - name: region-cluster-autoscaler
          image: IMAGE
          imagePullPolicy: IfNotPresent
          args:
            - --v=4
            - --stderrthreshold=info
            - --address=:8086
            - --cluster-name=$(CLUSTER_NAME)
            - --node-group-auto-discovery=$(CLUSTER_AUTOSCALER_NODE_GROUP_AUTO_DISCOVERY)
          env:
            - name: AWS_REGION
              value: AWS_REGION
            - name: CLUSTER_NAME
              value: dev
            - name: CLUSTER_AUTOSCALER_NODE_GROUP_AUTO_DISCOVERY
              value: asg:tag=k8s.io/cluster-autoscaler/$(CLUSTER_NAME)
          ports:
            - name: grpc
              containerPort: 8086
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 100m
              memory: 300Mi
          volumeMounts:
            - name: server-cert
              mountPath: /etc/ssl/server-cert
              readOnly: true
      volumes:
        - name: server-cert
          secret:
            secretName: region-cluster-autoscaler-server-tls
            defaultMode: 0400
