apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
data:
  cloud-config: |-
    address: "region-cluster-autoscaler.kube-system.svc.cluster.local:8086"
    key: "/etc/ssl/client-cert/tls.key"
    cert: "/etc/ssl/client-cert/tls.crt"
    cacert: "/etc/ssl/client-cert/ca.crt"
    grpc_timeout: "10s"
