apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - 00-cert-manager.yaml
  - 10-external-grpc.yaml
  - 20-cluster-autoscaler-cloud-config.yaml
  - 30-cluster-autoscaler-rbac.yaml
  - 40-cluster-autoscaler.yaml
